# Generated by Django 2.2.24 on 2025-01-30 21:31

from django.db import migrations
import phonenumbers


def fill_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")

    for flat in Flat.objects.iterator():
        if flat.owners_phonenumber:
            try:
                parsed_phone = phonenumbers.parse(flat.owners_phonenumber, "RU")
                if phonenumbers.is_valid_number(parsed_phone):
                    flat.owner_pure_phone = phonenumbers.format_number(
                        parsed_phone, phonenumbers.PhoneNumberFormat.E164
                    )
                else:
                    flat.owner_pure_phone = None
            except phonenumbers.NumberParseException:
                flat.owner_pure_phone = None
            flat.save(update_fields=["owner_pure_phone"])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(fill_owner_pure_phone),
    ]
