# Generated by Django 2.2.24 on 2025-01-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20250131_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(related_name='owned_by', to='property.Flat', verbose_name='Квартиры'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='flats_owned', to='property.Owner', verbose_name='Собственники квартиры'),
        ),
    ]
