# Generated by Django 2.2.24 on 2025-01-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20250131_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(related_name='owned_by', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
