# Generated by Django 2.2.24 on 2025-01-30 23:17

from django.db import migrations


def transfer_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(
            full_name=flat.owner,
            phone_number=flat.owners_phonenumber,
            normalized_phone=flat.owner_pure_phone
        )
        owner.flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20250131_0205'),
    ]

    operations = [
        migrations.RunPython(transfer_owners),
    ]
