# Generated by Django 2.2.24 on 2025-02-04 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20250204_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='flats',
        ),
    ]
